CREATE TABLE transactions (
  txn_id BIGINT PRIMARY KEY,
  amount DOUBLE PRECISION NOT NULL,
  ingested_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE transaction_features (
  txn_id BIGINT PRIMARY KEY REFERENCES transactions(txn_id),
  v1 DOUBLE PRECISION, v2 DOUBLE PRECISION, v3 DOUBLE PRECISION, v4 DOUBLE PRECISION,
  v5 DOUBLE PRECISION, v6 DOUBLE PRECISION, v7 DOUBLE PRECISION, v8 DOUBLE PRECISION,
  v9 DOUBLE PRECISION, v10 DOUBLE PRECISION, v11 DOUBLE PRECISION, v12 DOUBLE PRECISION,
  v13 DOUBLE PRECISION, v14 DOUBLE PRECISION, v15 DOUBLE PRECISION, v16 DOUBLE PRECISION,
  v17 DOUBLE PRECISION, v18 DOUBLE PRECISION, v19 DOUBLE PRECISION, v20 DOUBLE PRECISION,
  v21 DOUBLE PRECISION, v22 DOUBLE PRECISION, v23 DOUBLE PRECISION, v24 DOUBLE PRECISION,
  v25 DOUBLE PRECISION, v26 DOUBLE PRECISION, v27 DOUBLE PRECISION, v28 DOUBLE PRECISION
);

CREATE TABLE fraud_labels (
  txn_id BIGINT PRIMARY KEY REFERENCES transactions(txn_id),
  is_fraud SMALLINT NOT NULL CHECK (is_fraud IN (0, 1))
);
